-- require('podron.packer')
require('podron.remap')
require('podron.telescope')
require('podron.lspconfig')
require('podron.colorscheme')
require('podron.term')
require('podron.diagnostic')
require('podron.statusbar')
require('podron.gosetting')
require('podron._set')
